# Generated by Django 3.1.4 on 2020-12-30 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_accounts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.banks', verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='name',
            field=models.CharField(choices=[('mx', 'México')], max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='statususer',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Status User'),
        ),
    ]
